//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminClient.Resources.Localizations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование.
        /// </summary>
        public static string AdminWindow_Title {
            get {
                return ResourceManager.GetString("AdminWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График.
        /// </summary>
        public static string ChartMenuItem_Title {
            get {
                return ResourceManager.GetString("ChartMenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество посетителей.
        /// </summary>
        public static string ChartPage_Title {
            get {
                return ResourceManager.GetString("ChartPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечная дата:.
        /// </summary>
        public static string EndDate_Label {
            get {
                return ResourceManager.GetString("EndDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при соединении с сервером.
        /// </summary>
        public static string ErrorWhileConnecting_Content {
            get {
                return ResourceManager.GetString("ErrorWhileConnecting_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День.
        /// </summary>
        public static string GroupByDay_Item {
            get {
                return ResourceManager.GetString("GroupByDay_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Час.
        /// </summary>
        public static string GroupByHour_Item {
            get {
                return ResourceManager.GetString("GroupByHour_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минута.
        /// </summary>
        public static string GroupByMinute_Item {
            get {
                return ResourceManager.GetString("GroupByMinute_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц.
        /// </summary>
        public static string GroupByMonth_Item {
            get {
                return ResourceManager.GetString("GroupByMonth_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группировка:.
        /// </summary>
        public static string Grouping_Label {
            get {
                return ResourceManager.GetString("Grouping_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information_Title {
            get {
                return ResourceManager.GetString("Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string ProcessRange_Conent {
            get {
                return ResourceManager.GetString("ProcessRange_Conent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обработке скрипта.
        /// </summary>
        public static string ScriptError_Content {
            get {
                return ResourceManager.GetString("ScriptError_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрипт.
        /// </summary>
        public static string ScriptMenuItem_Title {
            get {
                return ResourceManager.GetString("ScriptMenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрипт пока ещё не существует. Загрузить пример скрипта?.
        /// </summary>
        public static string ScriptNotExists_Content {
            get {
                return ResourceManager.GetString("ScriptNotExists_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string SendScript_Content {
            get {
                return ResourceManager.GetString("SendScript_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальная дата:.
        /// </summary>
        public static string StartDate_Label {
            get {
                return ResourceManager.GetString("StartDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест.
        /// </summary>
        public static string TestScript_Content {
            get {
                return ResourceManager.GetString("TestScript_Content", resourceCulture);
            }
        }
    }
}
