//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.22 at 11:25:43 AM MSK 
//


package ru.lumberjackcode.vacls.client.applicationparams;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotKeys complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HotKeys">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CloseWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ForceShot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotKeys", propOrder = {
    "closeWindow",
    "forceShot"
})
public class HotKeys {

    @XmlElement(name = "CloseWindow", required = true)
    protected String closeWindow;
    @XmlElement(name = "ForceShot", required = true)
    protected String forceShot;

    /**
     * Gets the value of the closeWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseWindow() {
        return closeWindow;
    }

    /**
     * Sets the value of the closeWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseWindow(String value) {
        this.closeWindow = value;
    }

    /**
     * Gets the value of the forceShot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForceShot() {
        return forceShot;
    }

    /**
     * Sets the value of the forceShot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForceShot(String value) {
        this.forceShot = value;
    }

}
