//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.22 at 11:25:43 AM MSK 
//


package ru.lumberjackcode.vacls.client.applicationparams;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.lumberjackcode.vacls.client.applicationparams package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VaclsClientParams_QNAME = new QName("", "VaclsClientParams");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.lumberjackcode.vacls.client.applicationparams
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VaclsClientParams }
     * 
     */
    public VaclsClientParams createVaclsClientParams() {
        return new VaclsClientParams();
    }

    /**
     * Create an instance of {@link HotKeys }
     * 
     */
    public HotKeys createHotKeys() {
        return new HotKeys();
    }

    /**
     * Create an instance of {@link ServerParams }
     * 
     */
    public ServerParams createServerParams() {
        return new ServerParams();
    }

    /**
     * Create an instance of {@link VideoParams }
     * 
     */
    public VideoParams createVideoParams() {
        return new VideoParams();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VaclsClientParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VaclsClientParams")
    public JAXBElement<VaclsClientParams> createVaclsClientParams(VaclsClientParams value) {
        return new JAXBElement<VaclsClientParams>(_VaclsClientParams_QNAME, VaclsClientParams.class, null, value);
    }

}
