//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.22 at 11:25:43 AM MSK 
//


package ru.lumberjackcode.vacls.client.applicationparams;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VaclsClientParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VaclsClientParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OpenCVPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServerParams" type="{}ServerParams"/>
 *         &lt;element name="VideoParams" type="{}VideoParams"/>
 *         &lt;element name="HotKeysParams" type="{}HotKeys"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VaclsClientParams", propOrder = {
    "id",
    "openCVPath",
    "serverParams",
    "videoParams",
    "hotKeysParams"
})
public class VaclsClientParams {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "OpenCVPath", required = true)
    protected String openCVPath;
    @XmlElement(name = "ServerParams", required = true)
    protected ServerParams serverParams;
    @XmlElement(name = "VideoParams", required = true)
    protected VideoParams videoParams;
    @XmlElement(name = "HotKeysParams", required = true)
    protected HotKeys hotKeysParams;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the openCVPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenCVPath() {
        return openCVPath;
    }

    /**
     * Sets the value of the openCVPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenCVPath(String value) {
        this.openCVPath = value;
    }

    /**
     * Gets the value of the serverParams property.
     * 
     * @return
     *     possible object is
     *     {@link ServerParams }
     *     
     */
    public ServerParams getServerParams() {
        return serverParams;
    }

    /**
     * Sets the value of the serverParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerParams }
     *     
     */
    public void setServerParams(ServerParams value) {
        this.serverParams = value;
    }

    /**
     * Gets the value of the videoParams property.
     * 
     * @return
     *     possible object is
     *     {@link VideoParams }
     *     
     */
    public VideoParams getVideoParams() {
        return videoParams;
    }

    /**
     * Sets the value of the videoParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoParams }
     *     
     */
    public void setVideoParams(VideoParams value) {
        this.videoParams = value;
    }

    /**
     * Gets the value of the hotKeysParams property.
     * 
     * @return
     *     possible object is
     *     {@link HotKeys }
     *     
     */
    public HotKeys getHotKeysParams() {
        return hotKeysParams;
    }

    /**
     * Sets the value of the hotKeysParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotKeys }
     *     
     */
    public void setHotKeysParams(HotKeys value) {
        this.hotKeysParams = value;
    }

}
