//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.22 at 12:48:32 PM MSK 
//


package ru.lumberjackcode.vacls.server.applicationparams;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectionParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectionParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="portClient" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="portAdmin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectionParams", propOrder = {
    "portClient",
    "portAdmin"
})
public class ConnectionParams {

    @XmlElement(defaultValue = "8000")
    protected int portClient;
    @XmlElement(defaultValue = "5000")
    protected int portAdmin;

    /**
     * Gets the value of the portClient property.
     * 
     */
    public int getPortClient() {
        return portClient;
    }

    /**
     * Sets the value of the portClient property.
     * 
     */
    public void setPortClient(int value) {
        this.portClient = value;
    }

    /**
     * Gets the value of the portAdmin property.
     * 
     */
    public int getPortAdmin() {
        return portAdmin;
    }

    /**
     * Sets the value of the portAdmin property.
     * 
     */
    public void setPortAdmin(int value) {
        this.portAdmin = value;
    }

}
