//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.22 at 12:48:32 PM MSK 
//


package ru.lumberjackcode.vacls.server.applicationparams;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maxThreadPoolNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemParams", propOrder = {
    "maxThreadPoolNumber"
})
public class SystemParams {

    @XmlElement(defaultValue = "1")
    protected int maxThreadPoolNumber;

    /**
     * Gets the value of the maxThreadPoolNumber property.
     * 
     */
    public int getMaxThreadPoolNumber() {
        return maxThreadPoolNumber;
    }

    /**
     * Sets the value of the maxThreadPoolNumber property.
     * 
     */
    public void setMaxThreadPoolNumber(int value) {
        this.maxThreadPoolNumber = value;
    }

}
