//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.22 at 12:48:32 PM MSK 
//


package ru.lumberjackcode.vacls.server.applicationparams;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VaclsServerParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VaclsServerParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConnectionParams" type="{}ConnectionParams"/>
 *         &lt;element name="SystemParams" type="{}SystemParams"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VaclsServerParams", propOrder = {
    "connectionParams",
    "systemParams"
})
public class VaclsServerParams {

    @XmlElement(name = "ConnectionParams", required = true)
    protected ConnectionParams connectionParams;
    @XmlElement(name = "SystemParams", required = true)
    protected SystemParams systemParams;

    /**
     * Gets the value of the connectionParams property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionParams }
     *     
     */
    public ConnectionParams getConnectionParams() {
        return connectionParams;
    }

    /**
     * Sets the value of the connectionParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionParams }
     *     
     */
    public void setConnectionParams(ConnectionParams value) {
        this.connectionParams = value;
    }

    /**
     * Gets the value of the systemParams property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParams }
     *     
     */
    public SystemParams getSystemParams() {
        return systemParams;
    }

    /**
     * Sets the value of the systemParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParams }
     *     
     */
    public void setSystemParams(SystemParams value) {
        this.systemParams = value;
    }

}
